# Generated by Django 5.0.7 on 2024-08-13 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ar_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('icon', models.FileField(upload_to=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ar_name', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('icon', models.FileField(upload_to=None)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
